### ISSUE TITLE
Split getValues to get[Mixed/Numeric/String]Values

### ISSUE THREAD

**Issue by tzachshabtay** [slavik57/enum-values#14]
It's annoying to deal with a `[number | string]` array of enum values if I don't actually use mixed enums. Is it possible to split the `getValues` function into `getMixedValues` (the current version), `getNumericValues` (only returns `number`) and `getStringValues` (only returns `string`)?

For those last 2 versions, not sure if it's better to crash or ignore a mixed value.

**Comment by slavik57** [comment]
I added generic types to the relevant functions so now you can specify the value type you want:
```
EnumValues.getValues<number>(NumericValuesTestEnum); // will return number[]
EnumValues.getValues<string>(StringValuesTestEnum); // will return string[]
EnumValues.getValues(MixedEnum); // will return (string | number)[]
```

I will publish it soon

**Comment by slavik57** [comment]
Ok, check it now. 
Hope the solution is good enough

**Comment by tzachshabtay** [comment]
Wow, quick! Thanks, and yeah, generics is definitely a better solution than what I suggested.
