### ISSUE TITLE
git-flow-style "Develop" branch?

### ISSUE THREAD

**Issue by Zorgatone** [slavik57/enum-values#21]
You don't have a "develop" branch similar to how git-flow does?
I personally find it useful to merge in it PR you'll planning for a future release and still don't want to merge in master

**Comment by slavik57** [comment]
There are many git flows, I actually prefer always merging to master and not having a dev branch.
When I worked with dev branch we had always a lot of changes piled up on the dev branch and merging it to the master was a headache

**Comment by Zorgatone** [comment]
I see, I don't actually use the command-line tools myself, but I do apply some of the theories when working with branches manually

**Comment by Zorgatone** [comment]
It's ok then. Just asking :) just with master should be enough

**Comment by slavik57** [comment]
I do work with branches, I create a new branch every time I want to make a change. Usually, it is 1,2 or 3 commits and then the thing I wanted to do is done, I check all I need and merge the branch to master.
It is a continuous integration git-flow.
