### ISSUE TITLE
TypeScript 2.4 String Enums

### ISSUE THREAD

**Issue by mchambaud** [slavik57/enum-values#5]
Any plans to implement a solution for string enums?

**Comment by slavik57** [comment]
If I'm not mistaken they do not exist in runtime, only in compilation time, so I don't think it is possible. 
How would you use it? on the defined type? The type does not exist in runtime so you cannot use it

**Comment by mchambaud** [comment]
example
```
enum test {
    one = 't1',
    two = 't2',
    three = 't3'
}

for (let item in test) {
	if (isNaN(Number(item))) {
		console.log(item);
	}
}
```

result

```
one
t1
two
t2
three
t3
```

This sucks because lets say you want to use an string enum to fill a select box, you can't..?

**Comment by mchambaud** [comment]
Actually,

If you change the values to A,B and C I get this result

```
one
a
two
b
three
c
```
''
so keys with `index % 2` are values and others are keys, hmmm might be on something =D

**Comment by slavik57** [comment]
Ok, I thought you ment string literal types, my bad.
I will look into it in the next few days when I have some free time

**Comment by slavik57** [comment]
You can checkout now, I uploaded newer version to npm, should work.
